{% set version = "1.4-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-depmixs4
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/depmixS4_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/depmixS4/depmixS4_{{ version }}.tar.gz
  sha256: 587d1ec64709260a69dc55cb2ccff8ea209c206b7b519f3fc372d0657977a41d

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base >=3.6
    - r-mass
    - r-rsolnp
    - r-nlme
    - r-nnet
  run:
    - r-base >=3.6
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-rsolnp
    - r-nlme
    - r-nnet

test:
  commands:
    - $R -e "library('depmixS4')"           # [not win]
    - "\"%R%\" -e \"library('depmixS4')\""  # [win]

about:
  home: http://depmix.r-forge.r-project.org/
  license: GPL-2
  summary: Fits latent (hidden) Markov models on mixed categorical and continuous (time series)
    data, otherwise known as dependent mixture models, see Visser & Speekenbrink (2010,
    <DOI:10.18637/jss.v036.i07>).
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj

# Package: depmixS4
# Version: 1.4-0
# Date: 2019-07-10
# Title: Dependent Mixture Models - Hidden Markov Models of GLMs and Other Distributions in S4
# Author: Ingmar Visser <i.visser@uva.nl>, Maarten Speekenbrink <m.speekenbrink@ucl.ac.uk>
# Maintainer: Ingmar Visser <i.visser@uva.nl>
# Depends: R (>= 3.5.0), nnet, MASS, Rsolnp, nlme
# Imports: stats, stats4, methods
# Suggests: gamlss, gamlss.dist, Rdonlp2
# Additional_repositories: http://R-Forge.R-project.org
# Description: Fits latent (hidden) Markov models on mixed categorical and continuous (time series) data, otherwise known as dependent mixture models, see Visser & Speekenbrink (2010, <DOI:10.18637/jss.v036.i07>).
# License: GPL (>= 2)
# URL: http://depmix.r-forge.r-project.org/
# RoxygenNote: 6.1.0
# NeedsCompilation: yes
# Packaged: 2019-07-10 12:20:59 UTC; ingmar
# Repository: CRAN
# Date/Publication: 2019-07-10 14:02:32 UTC
