# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eBqyoDnCfF+lT3wlELhbA1bc5cYTXxyMfJe8ug7aIy1TvsiRjISoiU9nb9Gf4ArRpY37/igByT0i6+q9cDI8D6HP6EdFXRUQCQIQcaLshKYW8GWGKTRe2iXcC4GiCTetzZUKA/73nPuHcG1jWwsamuCVhTrO2/wo1cS7rGCNouK4mof0jotbsn4amRzULVjr131W3YrcSuiY+QwJ2R/hlQlscqykSlT7ZATkBvfSPDSyJLlu6YL3zFxrsySzMOeAmkkT0xDc0bPKFmP9ra3Jxx+7yifHafFGRiKzUhP5I6XOr7YPGYsQqpA1KV1PmzKq7brK008AwKZK7wTgXa2/T8qT0TMArq2dtFjA04q+PP5p/Ti6eYO1oVeNvkQdsI2XXvHpS0IbpigIn0mcgm7lBRw/vYiYzELvrspLGJiOZnr02DJL/myhFAkcp0xeCGt3swbetGAwacQJ7zSo4WVgXUKQxPdnx1EYJ+BLyaHoezESL7ohYbGWWvrnO1i1MKAm4+5prfeKnrz+nQCRGX1GYBx+XxodgzpY5rm7PA44eapGoJG9+LExXwi57AbmSbByovCedYoVp422f8gepWC/aN8JSD0sCjIph63dgq5jndqrg3SRoH3Dn5xUXOkWB3Y21fKZ8lRIy7iWweUlSuUvecW/YxZrgm+TsGGoiRjn8Cw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
