appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: eBqyoDnCfF+lT3wlELhbA1bc5cYTXxyMfJe8ug7aIy1TvsiRjISoiU9nb9Gf4ArRpY37/igByT0i6+q9cDI8D6HP6EdFXRUQCQIQcaLshKYW8GWGKTRe2iXcC4GiCTetzZUKA/73nPuHcG1jWwsamuCVhTrO2/wo1cS7rGCNouK4mof0jotbsn4amRzULVjr131W3YrcSuiY+QwJ2R/hlQlscqykSlT7ZATkBvfSPDSyJLlu6YL3zFxrsySzMOeAmkkT0xDc0bPKFmP9ra3Jxx+7yifHafFGRiKzUhP5I6XOr7YPGYsQqpA1KV1PmzKq7brK008AwKZK7wTgXa2/T8qT0TMArq2dtFjA04q+PP5p/Ti6eYO1oVeNvkQdsI2XXvHpS0IbpigIn0mcgm7lBRw/vYiYzELvrspLGJiOZnr02DJL/myhFAkcp0xeCGt3swbetGAwacQJ7zSo4WVgXUKQxPdnx1EYJ+BLyaHoezESL7ohYbGWWvrnO1i1MKAm4+5prfeKnrz+nQCRGX1GYBx+XxodgzpY5rm7PA44eapGoJG9+LExXwi57AbmSbByovCedYoVp422f8gepWC/aN8JSD0sCjIph63dgq5jndqrg3SRoH3Dn5xUXOkWB3Y21fKZ8lRIy7iWweUlSuUvecW/YxZrgm+TsGGoiRjn8Cw=}
bot:
  automerge: true
